// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "eu-west-1:574554a4-cf4e-454f-ad56-ef7daafb1c0e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rGKlMhLAR",
    "aws_user_pools_web_client_id": "1et7jno8sjdpnlrg6s7ihcq9k6",
    "aws_user_files_s3_bucket": "openclique-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};
export default awsmobile;
