export const FETCH_PLACE_NEAR_BY_REQUEST = 'FETCH_PLACE_NEAR_BY_REQUEST';
export const FETCH_PLACE_NEAR_BY_SUCCESS = 'FETCH_PLACE_NEAR_BY_SUCCESS';
export const FETCH_PLACE_NEAR_BY_FAILURE = 'FETCH_PLACE_NEAR_BY_FAILURE';
