export const ITEMS = [
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },

    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },

    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },

    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },

    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "common",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "uncommon",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "rare",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
    {
        name: "Item",
        total_drop: 10,
        users_drop: [0,1,2,3],
        url: "",
        type: "hat",
        rarity: "epic",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        height: 0,
        width: 0,
        id: "",
        value: ""
    },
]